#!/usr/bin/env python3
import sys
import os
import time
import argparse
import warnings
import atexit
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
warnings.filterwarnings("ignore")

from scripts.core.data_engine import DataMaster
from scripts.core.analysis_engine import AIAnalyst
from scripts.config import ASSETS, STRATEGIES
from scripts.core.data_monitor import DataHealthMonitor
from scripts.core.risk_engine import RiskManager

def goodbye():
    sys.stdout.flush()

atexit.register(goodbye)

class ZargulTrader:
    def __init__(self, train_all=False, run_once=False):
        print("\n🤖 Initializing Trading System...")
        self.data = DataMaster()
        self.ai = AIAnalyst(train_all)
        self.risk_manager = RiskManager()
        self.data_monitor = DataHealthMonitor()
        self.update_interval = 300
        self.run_once = run_once
        print("✅ System ready for trading.")

    def analyze_asset(self, asset):
        print("-" * 60)
        print(f"🔍 Analyzing {asset} at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        try:
            main_timeframe = STRATEGIES['main']['timeframe']
            df = self.data.get_data(asset, main_timeframe)
            
            # **CIRCUIT BREAKER**: If get_data returns None, stop analysis for this asset.
            if df is None:
                print(f"   - ❌ Skipping analysis for {asset} due to data failure.")
                return

            self.data_monitor.log_result(self.data.last_used_source, not df.empty)

            if len(df) < STRATEGIES['main']['sequence_length']:
                print(f"   - ⚠️ Insufficient data for {asset} on {main_timeframe} timeframe. Skipping analysis.")
                return

            print("   - Getting AI predictions for all strategies...")
            predictions = {}
            for strategy_name, strategy_config in STRATEGIES.items():
                timeframe = strategy_config['timeframe']
                df_strategy = self.data.get_data(asset, timeframe)

                if df_strategy is None:
                    print(f"   - ❌ Skipping {strategy_name} for {asset} due to data failure.")
                    predictions[strategy_name] = None
                    continue
                
                if len(df_strategy) < strategy_config['sequence_length']:
                    print(f"   - ⚠️ Insufficient data for {asset} on {timeframe} timeframe for {strategy_name}. Skipping.")
                    predictions[strategy_name] = None
                    continue
                
                if strategy_name == 'main':
                    predictions['main'] = self.ai.predict(asset, df_strategy)
                elif strategy_name == 'swing':
                    predictions['swing'] = self.ai.predict_swing(asset, df_strategy)
                elif strategy_name == 'scalp':
                    predictions['scalp'] = self.ai.predict_scalp(asset, df_strategy)

            for strategy_name, pred in predictions.items():
                print(f"\n   --- Strategy: {strategy_name.upper()} ---")
                if pred:
                    self._print_prediction(pred)
                    self._evaluate_trade(pred, strategy_name)
                else:
                    print("   │ No signal generated by the AI.")
        except Exception as e:
            print(f"💥 A critical error occurred while analyzing {asset}: {e}")
            import traceback
            traceback.print_exc()

    def _evaluate_trade(self, prediction, strategy_name):
        rules = STRATEGIES[strategy_name]
        if self.risk_manager.should_execute(prediction, strategy_name):
            print(f"   └ ✅ TRADE SIGNAL! {prediction['direction'].upper()} signal is valid.")
            self.log_trade(prediction, strategy_name)
        else:
            print(f"   └ ⚠️ Signal rejected by risk manager or strategy rules.")

    def _print_prediction(self, prediction):
        print(f"   │ Direction: {prediction['direction'].upper():<5} | Confidence: {prediction['confidence']*100: >3.0f}% | Move: {prediction['pct_change']: >5.2f}% | Current Price: ${prediction['current_price']:,.2f}")

    def log_trade(self, prediction, strategy_name):
        rules = STRATEGIES[strategy_name]
        levels = self.risk_manager.calculate_levels(prediction['current_price'], prediction['direction'], rules)
        log_entry = f"{prediction['timestamp'].isoformat()},{prediction['asset']},{prediction['direction']},{prediction['confidence']:.4f},{prediction['pct_change']:.4f},{strategy_name},{levels.get('stop_loss', 0):.4f},{levels.get('take_profit', 0):.4f}\n"
        try:
            with open("trading_journal.csv", "a") as f:
                if f.tell() == 0:
                    f.write("timestamp,asset,direction,confidence,pct_change,strategy_type,stop_loss,take_profit\n")
                f.write(log_entry)
            print("   └ 📝 Trade logged to trading_journal.csv")
        except IOError as e:
            print(f"   └ ❌ Error: Could not log trade to file: {e}")

    def run(self):
        print("\n🚀 Zargul Trader 2.0 - Live Operations Starting")
        print("=" * 60)
        while True:
            for asset in ASSETS:
                self.analyze_asset(asset)
            if self.run_once:
                print("\n✅ Run once complete.")
                break
            print("\n" + "=" * 60)
            print(f"⏳ Next analysis cycle in {self.update_interval / 60:.0f} minutes...")
            time.sleep(self.update_interval)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Zargul Trader 2.0")
    parser.add_argument('--train-all', action='store_true', help='Force retraining of all AI models.')
    parser.add_argument('--run-once', action='store_true', help='Run the analysis loop only once and then exit.')
    args = parser.parse_args()
    try:
        trader = ZargulTrader(train_all=args.train_all, run_once=args.run_once)
        trader.run()
    except Exception as e:
        print(f"\n💥 A fatal error occurred: {e}")
        sys.exit(1)